### PR TITLE
Nightly homebrew build

### PR DESCRIPTION
**Pull request by zbeekman**
Create a nightly test build using the Homebrew build formula.

This will let you know if someone makes a change in homebrew, macOS, or a dependency that breaks `bic` and will also let you know if changes made to `bic` will require fixing/updating the homebrew formula. (Or changes made to `bic` introduced bugs that manifest themselves when installed via the formula.)

### CODE REVIEW

**Comment by zbeekman** [comment]
I have no idea why macOS on Travis-CI is failing. FWIW, I've found macOS on Travis-CI to be pretty unreliable.

I haven't touched any actual code, so there's no reason that this should fail.

**Comment by hexagonal-sun** [comment]
Many thanks for the PR!  Will the nightly build happen on this repo or do I have to check the build status somewhere else?

Why Travis is failing is a mystery to me and I've had problems with it too.   What would you recommend for MacOS CI?

**Comment by zbeekman** [comment]
> Will the nightly build happen on this repo or do I have to check the build status somewhere else?

The nightly build will show up in the ["actions" tab](https://github.com/hexagonal-sun/bic/actions) of this repository. For an example of what it looks like you can see it in action on my fork: https://github.com/zbeekman/bic/actions?query=workflow%3ANightly-Homebrew-Build

If you create a personal access token with gist and public repo scopes (this link will do it: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew) and then [save that in a secret](https://github.com/hexagonal-sun/bic/settings/secrets) named [`HOMEBREW_GIST_TOKEN`](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R26) this action *should*™️ also post the homebrew logs and detailed debug information to a new gist when there is a failure.

As it stands, this action will run on a schedule [at 06:45 (AM) UTC daily](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R12-R13) (late at night across the US), and also [on pushes when the workflow file is touched](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R3-R6), and [pull requests against `master` when the workflow file is touched](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R7-R11).

To prevent slamming the Bintray and Github API endpoints at a regular time [scheduled jobs sleep for a random amount of time, between 0 and 10 minutes](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R7-R11) before proceeding. (But not pushes or PRs that touch the workflow file.)

[Unless a PR is being tested](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R42) (in which case, you want to get a quick result) [Homebrew's package index is updated](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R42) before proceeding.

The build process includes [creation of a binary bottle](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R58-R62) which is homebrew's binary package format, and [uploads it as a build artifact](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R58-R62). You can [find it posted on the workflow run page](https://github.com/zbeekman/bic/actions/runs/43244971) (the link will be in this repo though, not my fork, once you merge) and download it to investigate and test its functionality. It can be installed with `brew install --force --force-bottle ./path/to/bic--HEAD-<short-sha>.catalina.bottle.tar.gz` on macOS system matching the GitHub actions macOS major version (Catalina) after unzipping it, and/or you can fully extract the tarball to explore the contents.

It also [shows and tests the linkage](https://github.com/zbeekman/bic/actions/runs/43244971). This is effectively like running `otool -L` and seeing which libraries are system libraries and which libraries are from other homebrew formulae, and whether or not there's a missing dependency because an additional formula is being linked in or if there's a broken link.

Next it [tests and audits the formula](https://github.com/zbeekman/bic/actions/runs/43244971) in a manner similar to what would be done during the Homebrew CI and bottling process. If a problem is encountered due to the audit, then [it uses the actions warning annotation](https://github.com/hexagonal-sun/bic/pull/42/files#diff-d9c553afc71067982023c694bd6d53a7R75) to [post an annotation to this workflow file](https://github.com/zbeekman/bic/commit/c4a64996dcdb2c036e70b391a017219e65cd4a60#annotation_122680663). The example linked is an error annotation, but it will be a warning going forwards.

Finally, if there was a failure (other than audit failure), [it will upload the logs to a gist](https://github.com/zbeekman/bic/commit/c4a64996dcdb2c036e70b391a017219e65cd4a60#annotation_122680663) if the github token was added as a secret as described above.

> Why Travis is failing is a mystery to me and I've had problems with it too. What would you recommend for MacOS CI?

I like using GitHub actions for macOS (and Linux and Windows) testing. In ~ 1-1.5 weeks I could try to help with setting this up.

**Comment by zbeekman** [comment]
Anything else needed from me to merge this?

**Comment by hexagonal-sun** [comment]
This looks good. Thanks for working on this and the thorough explanation.

Merging.

**Pull request merged**
